@host=http://localhost:5161
@hostId=94f4648c-9af6-4cc5-aca8-098a06286815
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlckFnZ3JlZ2F0ZS5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IkFtaWNoYWkiLCJmYW1pbHlfbmFtZSI6Ik1hbnRpbmJhbmQiLCJqdGkiOiI4OGU3OGE5ZC1lNGJjLTQyNjUtODA5OC03YjdiYjAxMWFmYzUiLCJleHAiOjE3MTUwMzEwNTUsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.vsxJULv9A5w-iJYc1xvV0hQzgVvrACOtgtcMV1AQ6ec

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Yummy Menu",
  "description": "A menu with yummy food",
  "sections": [
    {
      "name": "Appetizers",
      "description": "Starters",
      "items": [
        {
          "name": "Fried pickles",
          "description": "Deep fried pickles"
        }
      ]
    }
  ]
}