@host=http://localhost:5161

GET http://localhost:5161/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjM2FkYzVlMy04ZjNiLTRiYzYtOGI1Mi0zOWIyYTY1NDgyY2UiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6ImMzYTcwMTkyLWI4ODUtNDJkMi1hNGZjLTk2OTgxNDFkYWNlMCIsImV4cCI6MTcxNDY0NDI5OCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.JcoM0Zj8sLGgM8e2fAkZCS-QEE5v_9zgOTiDOgUb9MY